{% set version = "1.2.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-shinyloadtest
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/shinyloadtest_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/shinyloadtest/shinyloadtest_{{ version }}.tar.gz
  sha256: 3f3b2a2aa5c050f728115512fa20507e087f1151a0f47e78e3e12dc96b2cc707

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r6
    - r-curl
    - r-dplyr >=1.0.0
    - r-ggplot2
    - r-httpuv >=1.5.2
    - r-jsonlite
    - r-magrittr
    - r-rlang >=0.1.2
    - r-scales
    - r-stringr
    - r-svglite
    - r-vroom
    - r-websocket >=1.0.0
    - r-xml2
    - pandoc >=2.2
  run:
    - r-base
    - r-r6
    - r-curl
    - r-dplyr >=1.0.0
    - r-ggplot2
    - r-httpuv >=1.5.2
    - r-jsonlite
    - r-magrittr
    - r-rlang >=0.1.2
    - r-scales
    - r-stringr
    - r-svglite
    - r-vroom
    - r-websocket >=1.0.0
    - r-xml2
    - pandoc >=2.2

test:
  commands:
    - $R -e "library('shinyloadtest')"           # [not win]
    - "\"%R%\" -e \"library('shinyloadtest')\""  # [win]

about:
  home: https://rstudio.github.io/shinyloadtest/, https://github.com/rstudio/shinyloadtest
  license: GPL-3.0-only
  summary: Assesses the number of concurrent users 'shiny' applications are capable of supporting, and for directing application changes in order to support a higher number of users. Provides facilities for recording 'shiny' application sessions, playing recorded sessions against a target server at load, and analyzing the
    resulting metrics.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
